name: Build and Release Module

on:
  push:
    tags:
      - "v*"  # запускается на любой тег вида vX.Y.Z

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create fixed ZIP archive
        run: |
          # Создаём ZIP с фиксированным именем drama-director.zip
          zip -r drama-director.zip . -x "*.git*" -x ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: drama-director.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}